#! /usr/bin/env node
//-*- mode: js2;-*-

var databaseUrl = "test";
var collections = ["filterPolygons", "postings", "edits"];
var mongodb = require('mongodb');
var _ = require('underscore');
var db = require("mongojs").connect(databaseUrl, collections);

db.edits.findOne(function(err,edits) {
    console.log(edits);
});
