#! /usr/bin/env node
//-*- mode: js2;-*-

var databaseUrl = "test";
var collections = ["nycapt_postings", "nycapt_edits"];
var mongodb = require('mongodb');
var _ = require('underscore');
var sprintf = require('sprintf').sprintf;
var fs = require('fs');
var db = require("mongojs").connect(databaseUrl, collections);

var dumpfile = 'dbdump.json';

db.nycapt_postings.find(function(err, postings) {
    db.nycapt_edits.find(function(err, edits) {
        fs.writeFile(dumpfile, JSON.stringify({
            'nycapt_postings' : postings,
            'nycapt_edits' : edits
        }), function() {
            console.log('wrote ' + dumpfile);
            db.close();
        });
    });
});
