#! /usr/bin/env node
//-*- mode: js2;-*-

var craigslist = require('./craigslist');
var sprintf = require('sprintf').sprintf;
var _ = require('underscore');
var fs = require('fs');


var region = "brk";

if (process.argv.length > 2) {
    region = process.argv[2];
}

if (region != "brk" && region != "mnh" && region != "jsy") {
    console.log("region must be one of brk, mnh, or jsy");
    process.exit();
}

var output_file = region + "-postings.json";

craigslist.getPostings("newyork.craigslist.org",
                       sprintf("/jsonsearch/sub/%s?maxAsk=2699", region),
                       function (postings) {
                           var counts = _.countBy(postings, function (item) {
                               if (item["GeoCluster"] !== undefined) {
                                   return "clusters";
                               } else {
                                   return "postings";
                               }
                           });
                           console.log(sprintf("got %1d postings, %1d of which are clusters",
                                               postings.length, 
                                               counts.clusters !== undefined ? counts.clusters : 0));
                           fs.writeFile(output_file, JSON.stringify(postings));
                           console.log('wrote results to ' + output_file);
                       },
                       {
                           resolveClusters : true,
                           requestTimeout: 10*60000,
                           timeout: 10*60000,
                           progressFunc : function(n) {
                               console.log(sprintf("outstanding requests: %1d", n));
                           }
                       });
