#! /usr/bin/env node
//-*- mode: js2;-*-

var databaseUrl = "test";
var collections = ["postings", "edits"];
var mongodb = require('mongodb');
var _ = require('underscore');
var sprintf = require('sprintf').sprintf;
var fs = require('fs');
var db = require("mongojs").connect(databaseUrl, collections);

var region = "brk";

if (process.argv.length > 2) {
    region = process.argv[2];
}

if (region != "brk" && region != "mnh" && region != "jsy") {
    console.log("region must be one of brk, mnh, or jsy");
    process.exit();
}

var load_file = region + "-postings.json";

var importDate = Number(((new Date()).getTime()/1000).toFixed(0)); // seconds since the epoch

/*
 * `withPidManager` calls its callback with an object having the following properties which represent the
 *     current state of the database:
 * 
 *              `postingIDByPid`: an object which maps Pids (the object's properties) to PostingIDs (property values)
 *              `pidByPostingID`: ab object which maps PostingIDs (the object's properties) to Pids (property values)
 *     `generatePid(postingID)` : a function that creates and returns a unique Pid for a postingID; this function
 *                                does not modify any postings --- it simply returns the Pid value
 */
function withPidManager(callback) {
    var maxPid = 0,
        postingIDByPid = {},
        pidByPostingID = {};
    db.edits.find(function(err,edits) {
        _.each(edits, function(edit) {
            postingIDByPid[edit.Pid] = edit.PostingID;
            pidByPostingID[edit.PostingID] = edit.Pid;
            if (edit.Pid > maxPid) {
                maxPid = edit.Pid;
            }
        });
        callback({
            'postingIDByPid' : postingIDByPid,
            'pidByPostingID' : pidByPostingID,
            'generatePid'    : function(postingID) {
                ++maxPid;
                postingIDByPid[maxPid] = postingID;
                pidByPostingID[postingID] = maxPid;
                return maxPid;
            }
        });
    });
}

function loadpostings(postings, pidManager) {
    var nPostings = postings.length,
        nDone = 0;
    function postingDone() {
        ++nDone;
        if (nDone >= nPostings) {
            db.close();
            console.log(sprintf('loaded %1d postings from file %s', nDone, load_file));
        }
    }
    _.each(postings, function(posting) {
        db.postings.find({"PostingID": posting.PostingID}, function(err, result) {
            var pid,
                isnew = false,
                postedDateModified = false;
            if (result.length === 1) {
                // a posting with this ID is already in the database; get its pid
                pid = pidManager.pidByPostingID[posting.PostingID];
                // and determine how its PostedDate has changed, if it has
                if (posting.PostedDate > result[0].PostedDate) {
                    postedDateModified = "newer";
                } else if (posting.PostedDate < result[0].PostedDate) {
                    postedDateModified = "OLDER [!!??]";
                }
            } else if (result.length === 0) {
                // this is a new posting; create a new edit doc for it
                isnew = true;
                pid = pidManager.generatePid(posting.PostingID);
                db.edits.save({
                    'Pid'        : pid,
                    'PostingID'  : posting.PostingID,
                    'ImportDate' : importDate,
                    'Tags'       : ["new"]
                }, function(err,value) {
                    if (err) {
                        console.log(sprintf("error saving edits for id=%s", posting.PostingID));
                    }
                });
            } else {
                // print error!
                console.log('error!');
                console.log(result.length);
                console.log(result);
                postingDone();
                return;
            }
            db.postings.update({"PostingID": posting.PostingID},
                               posting,
                               { upsert : true },
                               function(err) {
                                   if (isnew) {
                                       console.log(sprintf("saved new posting pid=%1d [craigslist id=%s]", pid, posting.PostingID));
                                   } else {
                                       if (postedDateModified) {
                                           console.log(sprintf("updated posting pid=%1d [craigslist id=%s] with %s PostedDate",
                                                               pid, posting.PostingID, postedDateModified));
                                       } else {
                                           console.log(sprintf("refreshed posting pid=%1d [craigslist id=%s]", pid, posting.PostingID));
                                       }
                                   }
                                   postingDone();
                               });
        });

    });
}

fs.readFile(load_file, 'utf8', function (err, data) {
    if (err) {
        console.log('Error: ' + err);
        return;
    }
    withPidManager(function(pidManager) {
        loadpostings(JSON.parse(data), pidManager);
    });
});
