#! /usr/bin/node

var csv2obj = require('./csv2obj');
var _ = require('underscore');

var routekeys = [
     'Route_1',
     'Route_2',
     'Route_3',
     'Route_4',
     'Route_5',
     'Route_6',
     'Route_7',
     'Route_8',
     'Route_9',
     'Route_10',
     'Route_11'
];


csv2obj('StationEntrances.csv', function(csv) {
    var stations = [];
    _.each(csv.data, function(station) {
        var routes = _.filter(_.map(routekeys, function(key) { return station[key]; }),
                              function(route) { return (route !== "" && route !== undefined); });
        stations.push({
            'nm'  : station.Station_Name,
            'rts'  : routes,
            'lat' : station.Latitude,
            'lng' : station.Longitude
        });
    });
    console.log(JSON.stringify(stations));
});

//     'Division',
//     'Line',
//     'Station_Name',
//     'Station_Latitude',
//     'Station_Longitude',
//     'Route_1',
//     'Route_2',
//     'Route_3',
//     'Route_4',
//     'Route_5',
//     'Route_6',
//     'Route_7',
//     'Route_8',
//     'Route_9',
//     'Route_10',
//     'Route_11',
//     'Entrance_Type',
//     'Entry',
//     'Exit_Only',
//     'Vending',
//     'Staffing',
//     'Staff_Hours',
//     'ADA',
//     'ADA_Notes',
//     'Free_Crossover',
//     'North_South_Street',
//     'East_West_Street',
//     'Corner',
//     'Latitude',
//     'Longitude'
