#! /usr/bin/env node
//-*- mode: js2;-*-

var databaseUrl = "test";
var collections = ["nycapt_postings", "nycapt_edits", "filterPolygons"];
var mongodb = require('mongodb');
var _ = require('underscore');
var sprintf = require('sprintf').sprintf;
var fs = require('fs');
var db = require("mongojs").connect(databaseUrl, collections);

db.nycapt_postings.find(function(err, postings) {
    db.nycapt_edits.find(function(err, edits) {
        db.filterPolygons.find(function(err, filterPolygons) {
            console.log('database contains:');
            console.log(sprintf('    %1d filterPolygons', filterPolygons.length));
            console.log(sprintf('    %1d postings', postings.length));
            console.log(sprintf('    %1d edits', edits.length));
            db.close();
        });
    });
});
